server:
  port: 8880

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  public:
    key: classpath:app.pub

secrete:
  header: ${secrete.header}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: account-service
        url: /account-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: auth-service
        url: /auth-service/v3/api-docs
