name: Deploy Fake Bank to VPS

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Ir para o subdiretório do projeto
      working-directory: ./03-01-spring-web/fake-bank
      run: echo "Entrando no projeto fake-bank..."

    - name: Criar arquivos RSA
      working-directory: ./03-01-spring-web/fake-bank
      run: |
        echo -e "${{ secrets.RSA_PRIVATE_KEY }}" > src/main/resources/app.key
        echo -e "${{ secrets.RSA_PUBLIC_KEY }}" > src/main/resources/app.pub

    - name: Build com Maven
      working-directory: ./03-01-spring-web/fake-bank
      run: mvn clean package -DskipTests

    - name: Copiar JAR para VPS via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: 03-01-spring-web/fake-bank/target/*.jar
        target: /srv/http/api-fake-bank


    - name: SSH e reiniciar o serviço
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart fakebank-api.service
